ALTER TABLE Payment DROP CONSTRAINT IF EXISTS FK_Payment_Type;
ALTER TABLE Payment DROP CONSTRAINT IF EXISTS FK_Payment_Student;
ALTER TABLE Mark DROP CONSTRAINT IF EXISTS FK_Mark_Student;
ALTER TABLE Mark DROP CONSTRAINT IF EXISTS FK_Mark_Subject;

-- Add foreign key constraints with ON DELETE CASCADE
ALTER TABLE Payment ADD CONSTRAINT FK_Payment_Type FOREIGN KEY (type_id) REFERENCES PaymentType(id) ON DELETE CASCADE;
ALTER TABLE Payment ADD CONSTRAINT FK_Payment_Student FOREIGN KEY (student_id) REFERENCES Student(id) ON DELETE CASCADE;
ALTER TABLE Mark ADD CONSTRAINT FK_Mark_Student FOREIGN KEY (student_id) REFERENCES Student(id) ON DELETE CASCADE;
ALTER TABLE Mark ADD CONSTRAINT FK_Mark_Subject FOREIGN KEY (subject_id) REFERENCES Subject(id) ON DELETE CASCADE;